version: "3.8"

services:
  app:
    build: .
    container_name: url_shortener_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=verysecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  db:
    image: postgres:13
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: url_shortener_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: